CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    north_item_number VARCHAR(50),
    south_item_number VARCHAR(50),
    description1 VARCHAR(255),
    description2 VARCHAR(255),
    brand VARCHAR(100),
    vendor_item_number VARCHAR(50),
    msrp VARCHAR(50),
    map_price VARCHAR(50),
    bar_code VARCHAR(50),
    rhlh VARCHAR(50) NULL,
    color1 VARCHAR(50),
    color2 VARCHAR(50),
    size VARCHAR(50),
    product_length VARCHAR(50),
    product_width VARCHAR(50),
    product_height VARCHAR(50),
    weight VARCHAR(50),
    bullet_features TEXT,
    extended_text TEXT,
    country_of_origin VARCHAR(100),
    flammable VARCHAR(50) NULL,
    hazardous VARCHAR(50) NULL,
    date_created VARCHAR(50),
    item_category_code VARCHAR(50),
    product_group_code VARCHAR(50),
    product_sub_group1 VARCHAR(50),
    product_sub_group2 VARCHAR(50),
    pack_size VARCHAR(50),
    inactive VARCHAR(10),
    blocked VARCHAR(10),
    name VARCHAR(255),
    include_exclude_group VARCHAR(50) NULL,
    prop65_applies VARCHAR(50) NULL,
    prop65_cancer_harm VARCHAR(50) NULL,
    prop65_reproductive_harm VARCHAR(50) NULL,
    prop65_chemical VARCHAR(255) NULL
);
